# Do not delete this file
dataset: "MNIST"
split: "dirichlet"
iid: False
num_clients: 100
num_classes: 10
sub_classes:
dim: 60
alpha: 0.5
beta: 0.5
sigma: 0.
shard_size: 150
mean_samples: 300
min_samples: 100
max_samples: 500
train_frac: 0.75
save_dir: "./processed_data"
format: "json"